<?php
/**
 * Class ModData
 *
 * @created      15.08.2026
 * @author       smiley <smiley@chillerlan.net>
 * @copyright    2026 smiley
 * @license      MIT
 */
declare(strict_types=1);

namespace Buildwars\GWSkillData\Equipment;

use Buildwars\GWSkillData\Common\{
	Attribute as A,
	Condition as Con,
	DamageType as DT,
	Effect as E,
	EffectCondition as EC,
	Profession as P,
};
use Buildwars\GWSkillData\Equipment\{
	AttributeRune as Arn,
	CommonRune as Crn,
	Inscription as Isc,
	Insignia as Ins,
	ItemType as T,
	WeaponPrefix as Pre,
	WeaponSuffix as Suf
};
use Closure;
use InvalidArgumentException;
use function array_combine;
use function array_key_exists;

final class ModData extends EquipmentDataAbstract{

	public const array DATA = [
		1   => [1,   Mod::PREFIX,      Pre::ICY,        T::AXE,     null,            null,                   19872,  [[DT::COLD, null]], ],
		2   => [2,   Mod::PREFIX,      Pre::EBON,       T::AXE,     null,            null,                   19872,  [[DT::EARTH, null]], ],
		3   => [3,   Mod::PREFIX,      Pre::SHOCKING,   T::AXE,     null,            null,                   19872,  [[DT::LIGHTNING, null]], ],
		4   => [4,   Mod::PREFIX,      Pre::FIERY,      T::AXE,     null,            null,                   19872,  [[DT::FIRE, null]], ],
		5   => [5,   Mod::PREFIX,      Pre::ICY,        T::BOW,     null,            null,                   91655,  [[DT::COLD, null]], ],
		6   => [6,   Mod::PREFIX,      Pre::EBON,       T::BOW,     null,            null,                   91655,  [[DT::EARTH, null]], ],
		7   => [7,   Mod::PREFIX,      Pre::SHOCKING,   T::BOW,     null,            null,                   91655,  [[DT::LIGHTNING, null]], ],
		8   => [8,   Mod::PREFIX,      Pre::FIERY,      T::BOW,     null,            null,                   91655,  [[DT::FIRE, null]], ],
		9   => [9,   Mod::PREFIX,      Pre::ICY,        T::HAMMER,  null,            null,                   19873,  [[DT::COLD, null]], ],
		10  => [10,  Mod::PREFIX,      Pre::EBON,       T::HAMMER,  null,            null,                   19873,  [[DT::EARTH, null]], ],
		11  => [11,  Mod::PREFIX,      Pre::SHOCKING,   T::HAMMER,  null,            null,                   19873,  [[DT::LIGHTNING, null]], ],
		12  => [12,  Mod::PREFIX,      Pre::FIERY,      T::HAMMER,  null,            null,                   19873,  [[DT::FIRE, null]], ],
		13  => [13,  Mod::PREFIX,      Pre::ICY,        T::SWORD,   null,            null,                   20015,  [[DT::COLD, null]], ],
		14  => [14,  Mod::PREFIX,      Pre::EBON,       T::SWORD,   null,            null,                   20015,  [[DT::EARTH, null]], ],
		15  => [15,  Mod::PREFIX,      Pre::SHOCKING,   T::SWORD,   null,            null,                   20015,  [[DT::LIGHTNING, null]], ],
		16  => [16,  Mod::PREFIX,      Pre::FIERY,      T::SWORD,   null,            null,                   20015,  [[DT::FIRE, null]], ],
		17  => [17,  Mod::PREFIX,      Pre::FURIOUS,    T::AXE,     null,            null,                   19872,  [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		18  => [18,  Mod::PREFIX,      Pre::FURIOUS,    T::HAMMER,  null,            null,                   19873,  [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		19  => [19,  Mod::PREFIX,      Pre::FURIOUS,    T::SWORD,   null,            null,                   20015,  [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		22  => [22,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MESMER,       A::FAST_CASTING,        23671,  null, ],
		23  => [23,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MESMER,       A::DOMINATION_MAGIC,    23671,  null, ],
		24  => [24,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MESMER,       A::ILLUSION_MAGIC,      23671,  null, ],
		25  => [25,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MESMER,       A::INSPIRATION_MAGIC,   23671,  null, ],
		26  => [26,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::NECROMANCER,  A::BLOOD_MAGIC,         23676,  null, ],
		27  => [27,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::NECROMANCER,  A::DEATH_MAGIC,         23676,  null, ],
		28  => [28,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::NECROMANCER,  A::CURSES,              23676,  null, ],
		29  => [29,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::NECROMANCER,  A::SOUL_REAPING,        23676,  null, ],
		30  => [30,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ELEMENTALIST, A::ENERGY_STORAGE,      23681,  null, ],
		31  => [31,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ELEMENTALIST, A::FIRE_MAGIC,          23681,  null, ],
		32  => [32,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ELEMENTALIST, A::AIR_MAGIC,           23681,  null, ],
		33  => [33,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ELEMENTALIST, A::EARTH_MAGIC,         23681,  null, ],
		34  => [34,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ELEMENTALIST, A::WATER_MAGIC,         23681,  null, ],
		35  => [35,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MONK,         A::HEALING_PRAYERS,     23686,  null, ],
		36  => [36,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MONK,         A::SMITING_PRAYERS,     23686,  null, ],
		37  => [37,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MONK,         A::PROTECTION_PRAYERS,  23686,  null, ],
		38  => [38,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::MONK,         A::DIVINE_FAVOR,        23686,  null, ],
		39  => [39,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::WARRIOR,      A::TACTICS,             23691,  null, ],
		40  => [40,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::WARRIOR,      A::STRENGTH,            23691,  null, ],
		41  => [41,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::WARRIOR,      A::AXE_MASTERY,         23691,  null, ],
		42  => [42,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::WARRIOR,      A::HAMMER_MASTERY,      23691,  null, ],
		43  => [43,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::WARRIOR,      A::SWORDMANSHIP,        23691,  null, ],
		44  => [44,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RANGER,       A::WILDERNESS_SURVIVAL, 23696,  null, ],
		45  => [45,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RANGER,       A::EXPERTISE,           23696,  null, ],
		46  => [46,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RANGER,       A::BEAST_MASTERY,       23696,  null, ],
		47  => [47,  Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RANGER,       A::MARKMANSHIP,         23696,  null, ],
		48  => [48,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MESMER,       A::FAST_CASTING,        151859, null, ],
		49  => [49,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MESMER,       A::DOMINATION_MAGIC,    151859, null, ],
		50  => [50,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MESMER,       A::ILLUSION_MAGIC,      151859, null, ],
		51  => [51,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MESMER,       A::INSPIRATION_MAGIC,   151859, null, ],
		52  => [52,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::NECROMANCER,  A::BLOOD_MAGIC,         151865, null, ],
		53  => [53,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::NECROMANCER,  A::DEATH_MAGIC,         151865, null, ],
		54  => [54,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::NECROMANCER,  A::CURSES,              151865, null, ],
		55  => [55,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::NECROMANCER,  A::SOUL_REAPING,        151865, null, ],
		56  => [56,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ELEMENTALIST, A::ENERGY_STORAGE,      151871, null, ],
		57  => [57,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ELEMENTALIST, A::FIRE_MAGIC,          151871, null, ],
		58  => [58,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ELEMENTALIST, A::AIR_MAGIC,           151871, null, ],
		59  => [59,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ELEMENTALIST, A::EARTH_MAGIC,         151871, null, ],
		60  => [60,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ELEMENTALIST, A::WATER_MAGIC,         151871, null, ],
		61  => [61,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MONK,         A::HEALING_PRAYERS,     151877, null, ],
		62  => [62,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MONK,         A::SMITING_PRAYERS,     151877, null, ],
		63  => [63,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MONK,         A::PROTECTION_PRAYERS,  151877, null, ],
		64  => [64,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::MONK,         A::DIVINE_FAVOR,        151877, null, ],
		65  => [65,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::WARRIOR,      A::TACTICS,             151883, null, ],
		66  => [66,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::WARRIOR,      A::STRENGTH,            151883, null, ],
		67  => [67,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::WARRIOR,      A::AXE_MASTERY,         151883, null, ],
		68  => [68,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::WARRIOR,      A::HAMMER_MASTERY,      151883, null, ],
		69  => [69,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::WARRIOR,      A::SWORDMANSHIP,        151883, null, ],
		70  => [70,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RANGER,       A::WILDERNESS_SURVIVAL, 151889, null, ],
		71  => [71,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RANGER,       A::EXPERTISE,           151889, null, ],
		72  => [72,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RANGER,       A::BEAST_MASTERY,       151889, null, ],
		73  => [73,  Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RANGER,       A::MARKMANSHIP,         151889, null, ],
		74  => [74,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MESMER,       A::FAST_CASTING,        151860, null, ],
		75  => [75,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MESMER,       A::DOMINATION_MAGIC,    151860, null, ],
		76  => [76,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MESMER,       A::ILLUSION_MAGIC,      151860, null, ],
		77  => [77,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MESMER,       A::INSPIRATION_MAGIC,   151860, null, ],
		78  => [78,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::NECROMANCER,  A::BLOOD_MAGIC,         151866, null, ],
		79  => [79,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::NECROMANCER,  A::DEATH_MAGIC,         151866, null, ],
		80  => [80,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::NECROMANCER,  A::CURSES,              151866, null, ],
		81  => [81,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::NECROMANCER,  A::SOUL_REAPING,        151866, null, ],
		82  => [82,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ELEMENTALIST, A::ENERGY_STORAGE,      151872, null, ],
		83  => [83,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ELEMENTALIST, A::FIRE_MAGIC,          151872, null, ],
		84  => [84,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ELEMENTALIST, A::AIR_MAGIC,           151872, null, ],
		85  => [85,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ELEMENTALIST, A::EARTH_MAGIC,         151872, null, ],
		86  => [86,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ELEMENTALIST, A::WATER_MAGIC,         151872, null, ],
		87  => [87,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MONK,         A::HEALING_PRAYERS,     151878, null, ],
		88  => [88,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MONK,         A::SMITING_PRAYERS,     151878, null, ],
		89  => [89,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MONK,         A::PROTECTION_PRAYERS,  151878, null, ],
		90  => [90,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::MONK,         A::DIVINE_FAVOR,        151878, null, ],
		91  => [91,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      A::TACTICS,             151884, null, ],
		92  => [92,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      A::STRENGTH,            151884, null, ],
		93  => [93,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      A::AXE_MASTERY,         151884, null, ],
		94  => [94,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      A::HAMMER_MASTERY,      151884, null, ],
		95  => [95,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      A::SWORDMANSHIP,        151884, null, ],
		96  => [96,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RANGER,       A::WILDERNESS_SURVIVAL, 151890, null, ],
		97  => [97,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RANGER,       A::EXPERTISE,           151890, null, ],
		98  => [98,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RANGER,       A::BEAST_MASTERY,       151890, null, ],
		99  => [99,  Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RANGER,       A::MARKMANSHIP,         151890, null, ],
		100 => [100, Mod::PREFIX,      Pre::DEFENSIVE,  T::STAFF,   null,            null,                   164795, [[E::ARMOR, 5]], ],
		101 => [101, Mod::PREFIX,      Pre::BARBED,     T::AXE,     null,            null,                   19872,  [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		102 => [102, Mod::PREFIX,      Pre::BARBED,     T::SWORD,   null,            null,                   20015,  [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		103 => [103, Mod::PREFIX,      Pre::CRIPPLING,  T::AXE,     null,            null,                   19872,  [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		104 => [104, Mod::PREFIX,      Pre::CRIPPLING,  T::SWORD,   null,            null,                   20015,  [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		105 => [105, Mod::PREFIX,      Pre::CRUEL,      T::AXE,     null,            null,                   19872,  [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		106 => [106, Mod::PREFIX,      Pre::CRUEL,      T::HAMMER,  null,            null,                   19873,  [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		107 => [107, Mod::PREFIX,      Pre::CRUEL,      T::SWORD,   null,            null,                   20015,  [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		108 => [108, Mod::PREFIX,      Pre::INSIGHTFUL, T::STAFF,   null,            null,                   164795, [[E::ENERGY, 5]], ],
		109 => [109, Mod::PREFIX,      Pre::HALE,       T::STAFF,   null,            null,                   164795, [[E::HEALTH, 30]], ],
		110 => [110, Mod::PREFIX,      Pre::POISONOUS,  T::AXE,     null,            null,                   19872,  [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		111 => [111, Mod::PREFIX,      Pre::POISONOUS,  T::BOW,     null,            null,                   91655,  [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		112 => [112, Mod::PREFIX,      Pre::POISONOUS,  T::SWORD,   null,            null,                   20015,  [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		113 => [113, Mod::PREFIX,      Pre::HEAVY,      T::AXE,     null,            null,                   19872,  [[E::CON_DUR_INCREASE, Con::WEAKNESS], [EC::STACKING, null]], ],
		114 => [114, Mod::PREFIX,      Pre::HEAVY,      T::HAMMER,  null,            null,                   19873,  [[E::CON_DUR_INCREASE, Con::WEAKNESS], [EC::STACKING, null]], ],
		115 => [115, Mod::PREFIX,      Pre::ZEALOUS,    T::AXE,     null,            null,                   19872,  [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		116 => [116, Mod::PREFIX,      Pre::ZEALOUS,    T::HAMMER,  null,            null,                   19873,  [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		117 => [117, Mod::PREFIX,      Pre::ZEALOUS,    T::BOW,     null,            null,                   91655,  [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		118 => [118, Mod::PREFIX,      Pre::ZEALOUS,    T::SWORD,   null,            null,                   20015,  [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		119 => [119, Mod::PREFIX,      Pre::VAMPIRIC,   T::AXE,     null,            null,                   19872,  [[E::LIFE_DRAIN, 3], [E::HEALTH_REGEN, -1]], ],
		120 => [120, Mod::PREFIX,      Pre::VAMPIRIC,   T::HAMMER,  null,            null,                   19873,  [[E::LIFE_DRAIN, 5], [E::HEALTH_REGEN, -1]], ],
		121 => [121, Mod::PREFIX,      Pre::VAMPIRIC,   T::BOW,     null,            null,                   91655,  [[E::LIFE_DRAIN, 5], [E::HEALTH_REGEN, -1]], ],
		122 => [122, Mod::PREFIX,      Pre::VAMPIRIC,   T::SWORD,   null,            null,                   20015,  [[E::LIFE_DRAIN, 3], [E::HEALTH_REGEN, -1]], ],
		123 => [123, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::DERVISH,      A::MYSTICISM,           205901, null, ],
		124 => [124, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::DERVISH,      A::EARTH_PRAYERS,       205901, null, ],
		125 => [125, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::DERVISH,      A::SCYTHE_MASTERY,      205901, null, ],
		126 => [126, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::DERVISH,      A::WIND_PRAYERS,        205901, null, ],
		127 => [127, Mod::SUFFIX,      Suf::DEFENSE,    T::AXE,     null,            null,                   91650,  [[E::ARMOR, 5]], ],
		128 => [128, Mod::SUFFIX,      Suf::DEFENSE,    T::BOW,     null,            null,                   91653,  [[E::ARMOR, 5]], ],
		129 => [129, Mod::SUFFIX,      Suf::WARDING,    T::AXE,     null,            null,                   91650,  [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		130 => [130, Mod::SUFFIX,      Suf::WARDING,    T::BOW,     null,            null,                   91653,  [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		131 => [131, Mod::SUFFIX,      Suf::WARDING,    T::HAMMER,  null,            null,                   91654,  [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		132 => [132, Mod::SUFFIX,      Suf::WARDING,    T::STAFF,   null,            null,                   164796, [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		133 => [133, Mod::SUFFIX,      Suf::WARDING,    T::SWORD,   null,            null,                   91656,  [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		134 => [134, Mod::SUFFIX,      Suf::DEFENSE,    T::HAMMER,  null,            null,                   91654,  [[E::ARMOR, 5]], ],
		135 => [135, Mod::SUFFIX,      Suf::SHELTER,    T::AXE,     null,            null,                   91650,  [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		136 => [136, Mod::SUFFIX,      Suf::SHELTER,    T::BOW,     null,            null,                   91653,  [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		137 => [137, Mod::SUFFIX,      Suf::SHELTER,    T::HAMMER,  null,            null,                   91654,  [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		138 => [138, Mod::SUFFIX,      Suf::SHELTER,    T::STAFF,   null,            null,                   164796, [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		139 => [139, Mod::SUFFIX,      Suf::SHELTER,    T::SWORD,   null,            null,                   91656,  [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		140 => [140, Mod::SUFFIX,      Suf::DEFENSE,    T::STAFF,   null,            null,                   164796, [[E::ARMOR, 5]], ],
		141 => [141, Mod::SUFFIX,      Suf::DEFENSE,    T::SWORD,   null,            null,                   91656,  [[E::ARMOR, 5]], ],
		142 => [142, Mod::SUFFIX,      Suf::FORTITUDE,  T::AXE,     null,            null,                   91650,  [[E::HEALTH, 30]], ],
		143 => [143, Mod::SUFFIX,      Suf::FORTITUDE,  T::BOW,     null,            null,                   91653,  [[E::HEALTH, 30]], ],
		144 => [144, Mod::SUFFIX,      Suf::FORTITUDE,  T::HAMMER,  null,            null,                   91654,  [[E::HEALTH, 30]], ],
		145 => [145, Mod::SUFFIX,      Suf::FORTITUDE,  T::STAFF,   null,            null,                   164796, [[E::HEALTH, 30]], ],
		146 => [146, Mod::SUFFIX,      Suf::FORTITUDE,  T::SWORD,   null,            null,                   91656,  [[E::HEALTH, 30]], ],
		147 => [147, Mod::SUFFIX,      Suf::ENCHANTING, T::AXE,     null,            null,                   91650,  [[E::ENCH_DURATION, 20]], ],
		148 => [148, Mod::SUFFIX,      Suf::ENCHANTING, T::BOW,     null,            null,                   91653,  [[E::ENCH_DURATION, 20]], ],
		149 => [149, Mod::SUFFIX,      Suf::ENCHANTING, T::HAMMER,  null,            null,                   91654,  [[E::ENCH_DURATION, 20]], ],
		150 => [150, Mod::SUFFIX,      Suf::ENCHANTING, T::STAFF,   null,            null,                   164796, [[E::ENCH_DURATION, 20]], ],
		151 => [151, Mod::SUFFIX,      Suf::ENCHANTING, T::SWORD,   null,            null,                   91656,  [[E::ENCH_DURATION, 20]], ],
		152 => [152, Mod::SUFFIX,      Suf::MASTERY,    T::AXE,     null,            A::AXE_MASTERY,         91650,  [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		153 => [153, Mod::SUFFIX,      Suf::MASTERY,    T::BOW,     null,            A::MARKMANSHIP,         91653,  [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		154 => [154, Mod::SUFFIX,      Suf::MASTERY,    T::HAMMER,  null,            A::HAMMER_MASTERY,      91654,  [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		155 => [155, Mod::SUFFIX,      Suf::MASTERY,    T::SWORD,   null,            A::SWORDMANSHIP,        91656,  [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		156 => [156, Mod::SUFFIX,      Crn::MINOR,      T::ARMOR,   P::NONE,         null,                   151852, [[E::HEALTH, 30], [EC::NONSTACKING, null]], ],
		157 => [157, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::NONE,         null,                   151853, [[E::HEALTH, 41], [EC::NONSTACKING, null]], ],
		158 => [158, Mod::SUFFIX,      Crn::SUPERIOR,   T::ARMOR,   P::NONE,         null,                   151854, [[E::HEALTH, 50], [EC::NONSTACKING, null]], ],
		159 => [159, Mod::SUFFIX,      Crn::MINOR,      T::ARMOR,   P::WARRIOR,      null,                   23691,  [[E::W_ABSORPTION, 1], [EC::NONSTACKING, null]], ],
		160 => [160, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::WARRIOR,      null,                   151883, [[E::W_ABSORPTION, 2], [EC::NONSTACKING, null]], ],
		161 => [161, Mod::SUFFIX,      Crn::SUPERIOR,   T::ARMOR,   P::WARRIOR,      null,                   151884, [[E::W_ABSORPTION, 3], [EC::NONSTACKING, null]], ],
		162 => [162, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ASSASSIN,     A::CRITICAL_STRIKES,    164842, null, ],
		163 => [163, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ASSASSIN,     A::DAGGER_MASTERY,      164842, null, ],
		164 => [164, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ASSASSIN,     A::DEADLY_ARTS,         164842, null, ],
		165 => [165, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::ASSASSIN,     A::SHADOW_ARTS,         164842, null, ],
		166 => [166, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RITUALIST,    A::CHANNELING_MAGIC,    164849, null, ],
		167 => [167, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RITUALIST,    A::RESTORATION_MAGIC,   164849, null, ],
		168 => [168, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RITUALIST,    A::COMMUNING,           164849, null, ],
		169 => [169, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::RITUALIST,    A::SPAWNING_POWER,      164849, null, ],
		170 => [170, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ASSASSIN,     A::CRITICAL_STRIKES,    164843, null, ],
		171 => [171, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ASSASSIN,     A::DAGGER_MASTERY,      164843, null, ],
		172 => [172, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ASSASSIN,     A::DEADLY_ARTS,         164843, null, ],
		173 => [173, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::ASSASSIN,     A::SHADOW_ARTS,         164843, null, ],
		174 => [174, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RITUALIST,    A::CHANNELING_MAGIC,    164850, null, ],
		175 => [175, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RITUALIST,    A::RESTORATION_MAGIC,   164850, null, ],
		176 => [176, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RITUALIST,    A::COMMUNING,           164850, null, ],
		177 => [177, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::RITUALIST,    A::SPAWNING_POWER,      164850, null, ],
		178 => [178, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ASSASSIN,     A::CRITICAL_STRIKES,    164844, null, ],
		179 => [179, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ASSASSIN,     A::DAGGER_MASTERY,      164844, null, ],
		180 => [180, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ASSASSIN,     A::DEADLY_ARTS,         164844, null, ],
		181 => [181, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::ASSASSIN,     A::SHADOW_ARTS,         164844, null, ],
		182 => [182, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RITUALIST,    A::CHANNELING_MAGIC,    164851, null, ],
		183 => [183, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RITUALIST,    A::RESTORATION_MAGIC,   164851, null, ],
		184 => [184, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RITUALIST,    A::COMMUNING,           164851, null, ],
		185 => [185, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::RITUALIST,    A::SPAWNING_POWER,      164851, null, ],
		186 => [186, Mod::PREFIX,      Pre::ICY,        T::DAGGERS, null,            null,                   164837, [[DT::COLD, null]], ],
		187 => [187, Mod::PREFIX,      Pre::EBON,       T::DAGGERS, null,            null,                   164837, [[DT::EARTH, null]], ],
		188 => [188, Mod::PREFIX,      Pre::FIERY,      T::DAGGERS, null,            null,                   164837, [[DT::FIRE, null]], ],
		189 => [189, Mod::PREFIX,      Pre::SHOCKING,   T::DAGGERS, null,            null,                   164837, [[DT::LIGHTNING, null]], ],
		190 => [190, Mod::PREFIX,      Pre::ZEALOUS,    T::DAGGERS, null,            null,                   164837, [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		191 => [191, Mod::PREFIX,      Pre::VAMPIRIC,   T::DAGGERS, null,            null,                   164837, [[E::LIFE_DRAIN, 3], [E::HEALTH_REGEN, -1]], ],
		192 => [192, Mod::PREFIX,      Pre::BARBED,     T::DAGGERS, null,            null,                   164837, [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		193 => [193, Mod::PREFIX,      Pre::CRIPPLING,  T::DAGGERS, null,            null,                   164837, [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		194 => [194, Mod::PREFIX,      Pre::CRUEL,      T::DAGGERS, null,            null,                   164837, [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		195 => [195, Mod::PREFIX,      Pre::POISONOUS,  T::DAGGERS, null,            null,                   164837, [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		196 => [196, Mod::PREFIX,      Pre::SILENCING,  T::DAGGERS, null,            null,                   164837, [[E::CON_DUR_INCREASE, Con::DAZED], [EC::STACKING, null]], ],
		197 => [197, Mod::PREFIX,      Pre::FURIOUS,    T::DAGGERS, null,            null,                   164837, [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		198 => [198, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::PARAGON,      A::LEADERSHIP,          205908, null,                                                   ],
		199 => [199, Mod::SUFFIX,      Suf::MASTERY,    T::DAGGERS, null,            A::DAGGER_MASTERY,      164856, [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		200 => [200, Mod::SUFFIX,      Suf::DEFENSE,    T::DAGGERS, null,            null,                   164856, [[E::ARMOR, 5]], ],
		201 => [201, Mod::SUFFIX,      Suf::SHELTER,    T::DAGGERS, null,            null,                   164856, [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		202 => [202, Mod::SUFFIX,      Suf::WARDING,    T::DAGGERS, null,            null,                   164856, [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		203 => [203, Mod::SUFFIX,      Suf::ENCHANTING, T::DAGGERS, null,            null,                   164856, [[E::ENCH_DURATION, 20]], ],
		204 => [204, Mod::SUFFIX,      Suf::FORTITUDE,  T::DAGGERS, null,            null,                   164856, [[E::HEALTH, 30]], ],
		205 => [205, Mod::PREFIX,      Pre::BARBED,     T::BOW,     null,            null,                   91655,  [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		206 => [206, Mod::PREFIX,      Pre::CRIPPLING,  T::BOW,     null,            null,                   91655,  [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		207 => [207, Mod::PREFIX,      Pre::SILENCING,  T::BOW,     null,            null,                   91655,  [[E::CON_DUR_INCREASE, Con::DAZED], [EC::STACKING, null]], ],
		208 => [208, Mod::PREFIX,      Pre::SUNDERING,  T::AXE,     null,            null,                   19872,  [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		209 => [209, Mod::PREFIX,      Pre::SUNDERING,  T::BOW,     null,            null,                   91655,  [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		210 => [210, Mod::PREFIX,      Pre::SUNDERING,  T::HAMMER,  null,            null,                   19873,  [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		211 => [211, Mod::PREFIX,      Pre::SUNDERING,  T::SWORD,   null,            null,                   20015,  [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		212 => [212, Mod::PREFIX,      Pre::SUNDERING,  T::DAGGERS, null,            null,                   164837, [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		213 => [213, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::PARAGON,      A::MOTIVATION,          205908, null, ],
		214 => [214, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::PARAGON,      A::COMMAND,             205908, null, ],
		215 => [215, Mod::SUFFIX,      Arn::MINOR,      T::ARMOR,   P::PARAGON,      A::SPEAR_MASTERY,       205908, null, ],
		216 => [216, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::DERVISH,      A::MYSTICISM,           205906, null, ],
		217 => [217, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::DERVISH,      A::EARTH_PRAYERS,       205906, null, ],
		218 => [218, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::DERVISH,      A::SCYTHE_MASTERY,      205906, null, ],
		219 => [219, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::DERVISH,      A::WIND_PRAYERS,        205906, null, ],
		220 => [220, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::PARAGON,      A::LEADERSHIP,          205909, null, ],
		221 => [221, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::PARAGON,      A::MOTIVATION,          205909, null, ],
		222 => [222, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::PARAGON,      A::COMMAND,             205909, null, ],
		223 => [223, Mod::SUFFIX,      Arn::MAJOR,      T::ARMOR,   P::PARAGON,      A::SPEAR_MASTERY,       205909, null, ],
		224 => [224, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::DERVISH,      A::MYSTICISM,           205907, null, ],
		225 => [225, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::DERVISH,      A::EARTH_PRAYERS,       205907, null, ],
		226 => [226, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::DERVISH,      A::SCYTHE_MASTERY,      205907, null, ],
		227 => [227, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::DERVISH,      A::WIND_PRAYERS,        205907, null, ],
		228 => [228, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::PARAGON,      A::LEADERSHIP,          205910, null, ],
		229 => [229, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::PARAGON,      A::MOTIVATION,          205910, null, ],
		230 => [230, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::PARAGON,      A::COMMAND,             205910, null, ],
		231 => [231, Mod::SUFFIX,      Arn::SUPERIOR,   T::ARMOR,   P::PARAGON,      A::SPEAR_MASTERY,       205910, null, ],
		232 => [232, Mod::PREFIX,      Pre::ICY,        T::SCYTHE,  null,            null,                   205895, [[DT::COLD, null]], ],
		233 => [233, Mod::PREFIX,      Pre::EBON,       T::SCYTHE,  null,            null,                   205895, [[DT::EARTH, null]], ],
		234 => [234, Mod::PREFIX,      Pre::ZEALOUS,    T::SCYTHE,  null,            null,                   205895, [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		235 => [235, Mod::PREFIX,      Pre::VAMPIRIC,   T::SCYTHE,  null,            null,                   205895, [[E::LIFE_DRAIN, 3], [E::HEALTH_REGEN, -1]], ],
		236 => [236, Mod::PREFIX,      Pre::SUNDERING,  T::SCYTHE,  null,            null,                   205895, [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		237 => [237, Mod::PREFIX,      Pre::BARBED,     T::SCYTHE,  null,            null,                   205895, [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		238 => [238, Mod::PREFIX,      Pre::CRIPPLING,  T::SCYTHE,  null,            null,                   205895, [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		239 => [239, Mod::PREFIX,      Pre::CRUEL,      T::SCYTHE,  null,            null,                   205895, [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		240 => [240, Mod::PREFIX,      Pre::FURIOUS,    T::SCYTHE,  null,            null,                   205895, [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		241 => [241, Mod::PREFIX,      Pre::POISONOUS,  T::SCYTHE,  null,            null,                   205895, [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		242 => [242, Mod::PREFIX,      Pre::HEAVY,      T::SCYTHE,  null,            null,                   205895, [[E::CON_DUR_INCREASE, Con::WEAKNESS], [EC::STACKING, null]], ],
		243 => [243, Mod::SUFFIX,      Suf::MASTERY,    T::SCYTHE,  null,            A::SCYTHE_MASTERY,      205917, [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		244 => [244, Mod::SUFFIX,      Suf::DEFENSE,    T::SCYTHE,  null,            null,                   205917, [[E::ARMOR, 5]], ],
		245 => [245, Mod::SUFFIX,      Suf::SHELTER,    T::SCYTHE,  null,            null,                   205917, [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		246 => [246, Mod::SUFFIX,      Suf::WARDING,    T::SCYTHE,  null,            null,                   205917, [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		247 => [247, Mod::SUFFIX,      Suf::ENCHANTING, T::SCYTHE,  null,            null,                   205917, [[E::ENCH_DURATION, 20]], ],
		248 => [248, Mod::SUFFIX,      Suf::FORTITUDE,  T::SCYTHE,  null,            null,                   205917, [[E::HEALTH, 30]], ],
		249 => [249, Mod::PREFIX,      Pre::FIERY,      T::SPEAR,   null,            null,                   205896, [[DT::FIRE, null]], ],
		250 => [250, Mod::PREFIX,      Pre::SHOCKING,   T::SPEAR,   null,            null,                   205896, [[DT::LIGHTNING, null]], ],
		251 => [251, Mod::PREFIX,      Pre::ZEALOUS,    T::SPEAR,   null,            null,                   205896, [[E::ENERGY_ON_HIT, 1], [E::ENERGY_REGEN, -1]], ],
		252 => [252, Mod::PREFIX,      Pre::VAMPIRIC,   T::SPEAR,   null,            null,                   205896, [[E::LIFE_DRAIN, 3], [E::HEALTH_REGEN, -1]], ],
		253 => [253, Mod::PREFIX,      Pre::SUNDERING,  T::SPEAR,   null,            null,                   205896, [[E::ARMOR_PEN, 20], [EC::CHANCE, 20]], ],
		254 => [254, Mod::PREFIX,      Pre::BARBED,     T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		255 => [255, Mod::PREFIX,      Pre::CRIPPLING,  T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		256 => [256, Mod::PREFIX,      Pre::CRUEL,      T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		257 => [257, Mod::PREFIX,      Pre::FURIOUS,    T::SPEAR,   null,            null,                   205896, [[E::DOUBLE_ADRENALINE, null], [EC::CHANCE, 10]], ],
		258 => [258, Mod::PREFIX,      Pre::POISONOUS,  T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::POISON], [EC::STACKING, null]], ],
		259 => [259, Mod::PREFIX,      Pre::SILENCING,  T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::DAZED], [EC::STACKING, null]], ],
		260 => [260, Mod::PREFIX,      Pre::HEAVY,      T::SPEAR,   null,            null,                   205896, [[E::CON_DUR_INCREASE, Con::WEAKNESS], [EC::STACKING, null]], ],
		261 => [261, Mod::SUFFIX,      Suf::MASTERY,    T::SPEAR,   null,            A::SPEAR_MASTERY,       205921, [[E::ATTRIBUTE_BONUS, 1], [EC::CHANCE, 20]], ],
		262 => [262, Mod::SUFFIX,      Suf::DEFENSE,    T::SPEAR,   null,            null,                   205921, [[E::ARMOR, 5]], ],
		263 => [263, Mod::SUFFIX,      Suf::SHELTER,    T::SPEAR,   null,            null,                   205921, [[E::ARMOR, 7], [EC::VS_PHYSICAL, null]], ],
		264 => [264, Mod::SUFFIX,      Suf::WARDING,    T::SPEAR,   null,            null,                   205921, [[E::ARMOR, 7], [EC::VS_ELEMENTAL, null]], ],
		265 => [265, Mod::SUFFIX,      Suf::ENCHANTING, T::SPEAR,   null,            null,                   205921, [[E::ENCH_DURATION, 20]], ],
		266 => [266, Mod::SUFFIX,      Suf::FORTITUDE,  T::SPEAR,   null,            null,                   205921, [[E::HEALTH, 30]], ],
		267 => [267, Mod::SUFFIX,      Suf::ENDURANCE,  T::FOCUS,   null,            null,                   205913, [[E::HEALTH, 45], [EC::WHILE_IN_STANCE, null]], ],
		268 => [268, Mod::SUFFIX,      Suf::VALOR,      T::FOCUS,   null,            null,                   205913, [[E::HEALTH, 60], [EC::WHILE_HEXED, null]], ],
		269 => [269, Mod::PREFIX,      Pre::FIERY,      T::SCYTHE,  null,            null,                   205895, [[DT::FIRE, null]], ],
		270 => [270, Mod::PREFIX,      Pre::SHOCKING,   T::SCYTHE,  null,            null,                   205895, [[DT::LIGHTNING, null]], ],
		271 => [271, Mod::PREFIX,      Pre::ICY,        T::SPEAR,   null,            null,                   205896, [[DT::COLD, null]], ],
		272 => [272, Mod::PREFIX,      Pre::EBON,       T::SPEAR,   null,            null,                   205896, [[DT::EARTH, null]], ],
		273 => [273, Mod::PREFIX,      Pre::SWIFT,      T::STAFF,   null,            null,                   164795, [[E::HCT, null], [EC::CHANCE, 10]], ],
		274 => [274, Mod::SUFFIX,      Suf::DEVOTION,   T::STAFF,   null,            null,                   164796, [[E::HEALTH, 45], [EC::WHILE_ENCHANTED, null]], ],
		275 => [275, Mod::SUFFIX,      Suf::ENDURANCE,  T::STAFF,   null,            null,                   164796, [[E::HEALTH, 45], [EC::WHILE_IN_STANCE, null]], ],
		276 => [276, Mod::SUFFIX,      Suf::VALOR,      T::STAFF,   null,            null,                   164796, [[E::HEALTH, 60], [EC::WHILE_HEXED, null]], ],
		277 => [277, Mod::INSCRIPTION, Isc::MARTIAL,    T::MARTIAL, null,            null,                   205890, [[E::HSR, null], [EC::CHANCE, 10]], ],
		278 => [278, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::ENERGY, 5], [EC::WHILE_ENCHANTED, null]], ],
		279 => [279, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::ENERGY, 7], [EC::HEALTH_LT, 50]], ],
		280 => [280, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::ENERGY, 7], [EC::WHILE_HEXED, null]], ],
		281 => [281, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::HCT, null], [EC::CHANCE, 10]], ],
		282 => [282, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [EC::INSC_TMI, null]], ],
		283 => [283, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [EC::WHILE_ENCHANTED, null]], ],
		284 => [284, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::DAZED], [EC::STACKING, null]], ],
		285 => [285, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::WEAKNESS], [EC::STACKING, null]], ],
		286 => [286, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 20], [EC::WHILE_HEXED, null]], ],
		287 => [287, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [EC::WHILE_IN_STANCE, null]], ],
		288 => [288, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [E::ENERGY, -5]], ],
		289 => [289, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [[E::ARMOR, -10], [EC::WHILE_ATTACKING, null]]], ],
		290 => [290, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265847, [[[E::HEALTH, 15], [EC::ARMOR_CHEST, null]], [[E::HEALTH, 10], [EC::ARMOR_LEGS, null]], [[E::HEALTH, 5], [EC::ARMOR_OTHER, null]]], ],
		291 => [291, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265846, [[[E::ENERGY, 3], [EC::ARMOR_CHEST, null]], [[E::ENERGY, 2], [EC::ARMOR_LEGS, null]], [[E::ENERGY, 1], [EC::ARMOR_OTHER, null]]], ],
		292 => [292, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265848, [[E::ARMOR, 10], [EC::VS_PHYSICAL, null]], ],
		293 => [293, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265849, [[E::ARMOR, 10], [EC::WHILE_ATTACKING, null]], ],
		294 => [294, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265850, [[E::ARMOR, 10], [EC::COM_BLESSED, null]], ],
		295 => [295, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265851, [[E::ARMOR, 10], [EC::COM_HERALDS, null]], ],
		296 => [296, Mod::PREFIX,      Ins::COMMON,     T::ARMOR,   P::NONE,         null,                   265852, [[E::ARMOR, 10], [EC::WHILE_IN_STANCE, null]], ],
		297 => [297, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ASSASSIN,     null,                   265839, [[[E::ARMOR, 10], [EC::VS_PHYSICAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::BLUNT]]], ],
		298 => [298, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ASSASSIN,     null,                   265840, [[[E::ARMOR, 10], [EC::VS_PHYSICAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::PIERCING]]], ],
		299 => [299, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ASSASSIN,     null,                   265841, [[[E::ARMOR, 10], [EC::VS_PHYSICAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::SLASHING]]], ],
		300 => [300, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ASSASSIN,     null,                   265842, [[E::ARMOR, 15], [EC::WHILE_ATTACKING, null]], ],
		301 => [301, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MESMER,       null,                   265845, [[E::ARMOR, 15], [EC::WHILE_ACTIVATING, null]], ],
		302 => [302, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265853, [[E::N_BLOODSTAINED, null], [EC::NONSTACKING, null]], ],
		303 => [303, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265854, [[[E::N_TORMENTORS, 6], [EC::ARMOR_CHEST, null]], [[E::N_TORMENTORS, 4], [EC::ARMOR_LEGS, null]], [[E::N_TORMENTORS, 2], [EC::ARMOR_OTHER, null]]], ],
		304 => [304, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265856, [[E::ARMOR, 15], [EC::VS_DAMAGE_TYPE, DT::PIERCING]], ],
		305 => [305, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265857, [[[E::ARMOR, 5], [EC::N_MINION_MASTERS, 1]], [[E::ARMOR, 5], [EC::N_MINION_MASTERS, 3]], [[E::ARMOR, 5], [EC::N_MINION_MASTERS, 5]]], ],
		306 => [306, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265858, [[E::ARMOR, 20], [EC::N_BLIGHTERS, null]], ],
		307 => [307, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ELEMENTALIST, null,                   265860, [[[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::COLD]]], ],
		308 => [308, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ELEMENTALIST, null,                   265861, [[[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::EARTH]]], ],
		309 => [309, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ELEMENTALIST, null,                   265862, [[[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::FIRE]]], ],
		310 => [310, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ELEMENTALIST, null,                   265863, [[[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::LIGHTNING]]], ],
		311 => [311, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MONK,         null,                   265864, [[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], ],
		312 => [312, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MONK,         null,                   265865, [[E::ARMOR, 10], [EC::M_DISCIPLES, null]], ],
		313 => [313, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::WARRIOR,      null,                   265867, [[E::DMG_REDUCTION, 3]], ],
		314 => [314, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::WARRIOR,      null,                   265868, [[[E::W_LIEUTENANTS, null], [EC::NONSTACKING, null]], [[E::ARMOR, -20]]], ],
		315 => [315, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::WARRIOR,      null,                   265869, [[E::W_STONEFIST, null], [EC::NONSTACKING, null]], ],
		316 => [316, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::WARRIOR,      null,                   265870, [[E::ARMOR, 10], [EC::VS_ELEMENTAL, null]], ],
		317 => [317, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::WARRIOR,      A::STRENGTH,            265871, [[E::ARMOR, 20], [[EC::ATTRIBUTE_REQ13, A::STRENGTH], [EC::VS_ELEMENTAL, null]]], ],
		318 => [318, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265872, [[E::ARMOR, 15], [EC::VS_DAMAGE_TYPE, DT::COLD]], ],
		319 => [319, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265874, [[E::ARMOR, 15], [EC::VS_DAMAGE_TYPE, DT::FIRE]], ],
		320 => [320, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265875, [[E::ARMOR, 15], [EC::VS_DAMAGE_TYPE, DT::LIGHTNING]], ],
		321 => [321, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265877, [[E::ARMOR, 10], [EC::R_SCOUTS, null]], ],
		322 => [322, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RITUALIST,    null,                   265880, [[[E::ARMOR, 5], [EC::RT_SHAMANS, 1]], [[E::ARMOR, 5], [EC::RT_SHAMANS, 2]], [[E::ARMOR, 5], [EC::RT_SHAMANS, 3]]], ],
		323 => [323, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RITUALIST,    null,                   265881, [[E::ARMOR, 15], [EC::RT_GHOSTFORGE, null]], ],
		324 => [324, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RITUALIST,    null,                   265882, [[E::ARMOR, 15], [EC::WHILE_ACTIVATING, null]], ],
		325 => [325, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::WHILE_ENCHANTED, null]], ],
		326 => [326, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ENERGY, 15], [E::ENERGY_REGEN, -1]], ],
		327 => [327, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::HSR, null], [EC::CHANCE, 10]], ],
		328 => [328, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::HSR_ATTRIBUTE, null], [EC::CHANCE, 20]], ],
		329 => [329, Mod::INSCRIPTION, Isc::MARTIAL,    T::MARTIAL, null,            null,                   205890, [[E::ENERGY, 5]], ],
		330 => [330, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::DMG_REDUCTION, 5], [EC::CHANCE, 20]], ],
		331 => [331, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::DMG_REDUCTION, 2], [EC::WHILE_ENCHANTED, null]], ],
		332 => [332, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::DMG_REDUCTION, 3], [EC::WHILE_HEXED, null]], ],
		333 => [333, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::DMG_REDUCTION, 2], [EC::WHILE_IN_STANCE, null]], ],
		334 => [334, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ATTRIBUTE_ITEM, 1], [EC::CHANCE, 20]], ],
		335 => [335, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::HCT_ATTRIBUTE, null], [EC::CHANCE, 20]], ],
		336 => [336, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::ENERGY, 15], [E::ENERGY_REGEN, -1]], ],
		337 => [337, Mod::INSCRIPTION, Isc::CASTER,     T::CASTER,  null,            null,                   205889, [[E::ENERGY, 5], [EC::HEALTH_GT, 50]], ],
		338 => [338, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 15], [EC::HEALTH_GT, 50]], ],
		339 => [339, Mod::INSCRIPTION, Isc::WEAPONS,    T::WEAPONS, null,            null,                   205892, [[E::DAMAGE, 20], [EC::HEALTH_LT, 50]], ],
		340 => [340, Mod::SUFFIX,      Suf::FORTITUDE,  T::FOCUS,   null,            null,                   205913, [[E::HEALTH, 30]], ],
		341 => [341, Mod::SUFFIX,      Suf::DEVOTION,   T::FOCUS,   null,            null,                   205913, [[E::HEALTH, 45], [EC::WHILE_ENCHANTED, null]], ],
		342 => [342, Mod::SUFFIX,      Suf::SWIFTNESS,  T::FOCUS,   null,            null,                   205913, [[E::HCT, null], [EC::CHANCE, 10]], ],
		343 => [343, Mod::SUFFIX,      Suf::APTITUDE,   T::FOCUS,   null,            null,                   205913, [[E::HCT_ATTRIBUTE, null], [EC::CHANCE, 20]], ],
		344 => [344, Mod::SUFFIX,      Suf::QUICKENING, T::WAND,    null,            null,                   205916, [[E::HSR, null], [EC::CHANCE, 10]], ],
		345 => [345, Mod::SUFFIX,      Suf::MEMORY,     T::WAND,    null,            null,                   205916, [[E::HSR_ATTRIBUTE, null], [EC::CHANCE, 20]], ],
		346 => [346, Mod::SUFFIX,      Suf::FORTITUDE,  T::SHIELD,  null,            null,                   205920, [[E::HEALTH, 30]], ],
		347 => [347, Mod::SUFFIX,      Suf::DEVOTION,   T::SHIELD,  null,            null,                   205920, [[E::HEALTH, 45], [EC::WHILE_ENCHANTED, null]], ],
		348 => [348, Mod::SUFFIX,      Suf::ENDURANCE,  T::SHIELD,  null,            null,                   205920, [[E::HEALTH, 45], [EC::WHILE_IN_STANCE, null]], ],
		349 => [349, Mod::SUFFIX,      Suf::VALOR,      T::SHIELD,  null,            null,                   205920, [[E::HEALTH, 60], [EC::WHILE_HEXED, null]], ],
		350 => [350, Mod::PREFIX,      Pre::ADEPT,      T::STAFF,   null,            null,                   164795, [[E::HCT_ATTRIBUTE, null], [EC::CHANCE, 20]], ],
		351 => [351, Mod::SUFFIX,      Suf::MASTERY,    T::STAFF,   null,            null,                   164796, [[E::ATTRIBUTE_ITEM, 1], [EC::CHANCE, 20]], ],
		352 => [352, Mod::SUFFIX,      Crn::MINOR,      T::ARMOR,   P::NONE,         null,                   151852, [[E::ENERGY, 2]], ],
		353 => [353, Mod::SUFFIX,      Crn::MINOR,      T::ARMOR,   P::NONE,         null,                   151852, [[E::HEALTH, 10]], ],
		354 => [354, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::NONE,         null,                   151853, [[[E::CON_DUR_DECREASE, Con::DAZED], [EC::NONSTACKING, null]], [[E::CON_DUR_DECREASE, Con::DEEP_WOUND], [EC::NONSTACKING, null]]], ],
		355 => [355, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::NONE,         null,                   151853, [[[E::CON_DUR_DECREASE, Con::BLEEDING], [EC::NONSTACKING, null]], [[E::CON_DUR_DECREASE, Con::CRIPPLED], [EC::NONSTACKING, null]]], ],
		356 => [356, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::NONE,         null,                   151853, [[[E::CON_DUR_DECREASE, Con::BLIND], [EC::NONSTACKING, null]], [[E::CON_DUR_DECREASE, Con::WEAKNESS], [EC::NONSTACKING, null]]], ],
		357 => [357, Mod::SUFFIX,      Crn::MAJOR,      T::ARMOR,   P::NONE,         null,                   151853, [[[E::CON_DUR_DECREASE, Con::DISEASE], [EC::NONSTACKING, null]], [[E::CON_DUR_DECREASE, Con::POISON], [EC::NONSTACKING, null]]], ],
		358 => [358, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MESMER,       null,                   265843, [[E::ARMOR, 3], [EC::ME_ARTIFICERS, null]], ],
		359 => [359, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MESMER,       null,                   265844, [[[E::ARMOR, 5], [EC::WHILE_RECHARGING, 1]], [[E::ARMOR, 5], [EC::WHILE_RECHARGING, 3]], [[E::ARMOR, 5], [EC::WHILE_RECHARGING, 5]]], ],
		360 => [360, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::NECROMANCER,  null,                   265855, [[[E::ARMOR, 5], [EC::HEALTH_LT, 80]], [[E::ARMOR, 5], [EC::HEALTH_LT, 60]], [[E::ARMOR, 5], [EC::HEALTH_LT, 40]], [[E::ARMOR, 5], [EC::HEALTH_LT, 20]]], ],
		361 => [361, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::ELEMENTALIST, null,                   265859, [[[E::ARMOR, 5], [EC::ATTRIBUTE_REQ9, A::AIR_MAGIC]], [[E::ARMOR, 5], [EC::ATTRIBUTE_REQ9, A::EARTH_MAGIC]], [[E::ARMOR, 5], [EC::ATTRIBUTE_REQ9, A::FIRE_MAGIC]], [[E::ARMOR, 5], [EC::ATTRIBUTE_REQ9, A::WATER_MAGIC]]], ],
		362 => [362, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::MONK,         null,                   265866, [[[E::ARMOR, 5], [EC::WHILE_RECHARGING, 1]], [[E::ARMOR, 5], [EC::WHILE_RECHARGING, 3]], [[E::ARMOR, 5], [EC::WHILE_RECHARGING, 5]]], ],
		363 => [363, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265873, [[E::ARMOR, 15], [EC::VS_DAMAGE_TYPE, DT::EARTH]], ],
		364 => [364, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::RANGER,       null,                   265876, [[E::ARMOR, 10], [EC::R_BEASTMASTERS, null]], ],
		365 => [365, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::DERVISH,      null,                   265878, [[[E::ARMOR, 5], [EC::D_WINDWALKER, 1]], [[E::ARMOR, 5], [EC::D_WINDWALKER, 2]], [[E::ARMOR, 5], [EC::D_WINDWALKER, 3]], [[E::ARMOR, 5], [EC::D_WINDWALKER, 4]]], ],
		366 => [366, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::DERVISH,      null,                   265879, [[E::ARMOR, 10], [EC::D_FORSAKEN, null]], ],
		367 => [367, Mod::PREFIX,      Ins::PROFESSION, T::ARMOR,   P::PARAGON,      null,                   265883, [[E::ARMOR, 10], [EC::P_CENTURIONS, null]], ],
		368 => [368, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [E::ENERGY, -5]], ],
		369 => [369, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [E::HEALTH, -20]], ],
		370 => [370, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::VS_ELEMENTAL, null]], ],
		371 => [371, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::VS_PHYSICAL, null]], ],
		372 => [372, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::WHILE_ATTACKING, null]], ],
		373 => [373, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::WHILE_CASTING, null]], ],
		374 => [374, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 10], [EC::HEALTH_LT, 50]], ],
		375 => [375, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 5], [EC::HEALTH_GT, 50]], ],
		376 => [376, Mod::INSCRIPTION, Isc::FOCUS,      T::FOCUS,   null,            null,                   205889, [[E::ARMOR, 10], [EC::WHILE_HEXED, null]], ],
		377 => [377, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::BLUNT]], ],
		378 => [378, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::COLD]], ],
		379 => [379, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::EARTH]], ],
		380 => [380, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::LIGHTNING]], ],
		381 => [381, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::FIRE]], ],
		382 => [382, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::PIERCING]], ],
		383 => [383, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::ARMOR, 10], [EC::VS_DAMAGE_TYPE, DT::SLASHING]], ],
		384 => [384, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::BLEEDING], [EC::STACKING, null]], ],
		385 => [385, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::BLIND], [EC::STACKING, null]], ],
		386 => [386, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::CRIPPLED], [EC::STACKING, null]], ],
		387 => [387, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::DEEP_WOUND], [EC::STACKING, null]], ],
		388 => [388, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::DISEASE], [EC::STACKING, null]], ],
		389 => [389, Mod::INSCRIPTION, Isc::OFFHAND,    T::OFFHAND, null,            null,                   205891, [[E::CON_DUR_DECREASE, Con::POISON], [EC::STACKING, null]], ],
		// of the profession
		970 => [970, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::STRENGTH,            164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		971 => [971, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::EXPERTISE,           164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		972 => [972, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::DIVINE_FAVOR,        164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		973 => [973, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::SOUL_REAPING,        164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		974 => [974, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::FAST_CASTING,        164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		975 => [975, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::ENERGY_STORAGE,      164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		976 => [976, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::CRITICAL_STRIKES,    164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		977 => [977, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::SPAWNING_POWER,      164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		978 => [978, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::LEADERSHIP,          164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		979 => [979, Mod::SUFFIX,      Suf::PROFESSION, T::STAFF,   null,            A::MYSTICISM,           164796, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],

		980 => [980, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::STRENGTH,            205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		981 => [981, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::EXPERTISE,           205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		982 => [982, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::DIVINE_FAVOR,        205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		983 => [983, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::SOUL_REAPING,        205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		984 => [984, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::FAST_CASTING,        205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		985 => [985, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::ENERGY_STORAGE,      205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		986 => [986, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::CRITICAL_STRIKES,    205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		987 => [987, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::SPAWNING_POWER,      205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		988 => [988, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::LEADERSHIP,          205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
		989 => [989, Mod::SUFFIX,      Suf::PROFESSION, T::WAND,    null,            A::MYSTICISM,           205916, [[E::OF_PROFESSION, 5], [EC::ATTR_RANK_LT, null]], ],
	];

	public function map(Closure $callable):array{
		$result = [];

		foreach(self::DATA as $id => $row){
			$data = array_combine(Mod::KEYS_DATA, $row);

			$result[$id] = $callable(new Mod($data, $this->lang), $id);
		}

		return $result;
	}

	public function get(int $id):Mod{

		if(!array_key_exists($id, self::DATA)){
			throw new InvalidArgumentException('invalid equipment ID');
		}

		// name is set in the mod instance, inferred from the subtype
		$data = array_combine(Mod::KEYS_DATA, self::DATA[$id]);

		return new Mod($data, $this->lang);
	}

}
