name: incremental-update.yml

on:
  push:
    branches:
      - main
  schedule:
    # POSIX cron syntax (Fridays, 5pm), https://crontab.guru/#0_17_*_*_5
    - cron: "0 17 * * 5"

jobs:
  build-public:
    name: "publish files"
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v7

      - name: "Checkout previous gh-pages build"
        uses: actions/checkout@v7
        with:
          ref: "gh-pages"
          path: ".build/gh-pages-old"

      # the pawned build with hash check will only update changed databases
      - name: "Copy previous paw-ned² build files"
        run: |
          mkdir ./public/pawned
          cp .build/gh-pages-old/pawned/* ./public/pawned

      - name: "install dependencies"
        run: npm install

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}
          coverage: none

      - name: "Install dependencies with composer"
        uses: ramsey/composer-install@v4

      - name: "build"
        run: npm run build

      - name: "build-src"
        run: npm run build-src

      - name: "Build JSON and paw-ned² databases"
        run: php ./tools/build-continuous.php

      - name: "Copy files"
        run: |
          mkdir ./public/js
          cp ./dist/gw-skilldata-es6.js ./public/js
          cp ./dist/gw-skilldata-es6-src.js ./public/js
          cp ./dist/gw-skilldata-node.cjs ./public/js
          cp ./dist/gw-skilldata-node-src.cjs ./public/js
          mkdir ./public/json
          cp ./data/json-full/*.json ./public/json
          mkdir ./public/json/skills
          cp ./data/json-skills/*.json ./public/json/skills
          cp ./.build/*.ini ./public/pawned
          cp ./.build/*.csv ./public/pawned
          mkdir ./public/schemas
          cp ./data/schemas/*.schema.json ./public/schemas

      - name: "Publish files to gh-pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
